services:

    SiteBundle\:
        resource: '%kernel.project_dir%/src/SiteBundle/*'
        exclude: '%kernel.project_dir%/src/SiteBundle/{Entity,Repository,Tests,EventListener,Helper}'
        
    SiteBundle\Controller\:
        resource: '%kernel.project_dir%/src/SiteBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    SiteBundle\EventListener\RequestListener:
        arguments: ["@service_container", "@security.token_storage", "@fos_user.user_manager", "@doctrine.orm.entity_manager", "@router"]
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.request }
