services:

    CmsBundle\:
        resource: '%kernel.project_dir%/src/CmsBundle/*'
        exclude: '%kernel.project_dir%/src/CmsBundle/{Entity,Repository,Tests,EventListener,Helper}'
        
    CmsBundle\Controller\:
        resource: '%kernel.project_dir%/src/CmsBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    cms.cms_helper:
        class: CmsBundle\Helper\CmsHelper
        arguments: ["@service_container", "@security.token_storage", "@fos_user.user_manager", "@doctrine.orm.entity_manager", "@router"]
        public: true
